spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: false
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/secret_juju?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1111}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:google-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-secret}
            scope:
              - email
              - name
#          naver:
#            client-id: ${NAVER_CLIENT_ID:naver-id}
#            client-secret: ${NAVER_CLIENT_SECRET:naver-secret}
#            redirectUriTemplate: "localhost:6180/login/oauth2/code/naver"
#            authorization-grant-type: authorization_code
#            scope: name, email, profile_image
#            client-name: Naver
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

server:
  address: 0.0.0.0
  port: 6180

app:
  auth:
    tokenSecret: ${TOKEN_SECRET:aaaa}
    tokenExpirationMsec: ${TOKEN_EXPIRATION_MSEC:100000}
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect